
dist: bionic
language: generic

env:
  global:
    GIT_BRANCH: master


notifications:
  slack:
    secure: blcsCQhMgP/QpsYjkBQU0HeZsu0MCHjzEq8gTg1Hd38cK/qaRxT46q00MeXwypRSFaTCoUll10LCF81qlz50Q7deEW/v/F2oz1VnPRZi4+EPVkRprE3H2FDQokWiz2g45he8I90d6y6gBLtFxedDWR4vtKG1hGh+pKTBbLFe8TFtOJ6g3wPCMjwpFv8+yxTucPAv9qETcP82cjrQtR7v8oOge+HiKAQcdt2GAIY0N9MZqChcbQVoJxHTXpAIHOsarZwbtMdwl8Lmj0WrL9Ck7L4VnAKvQha/miMPksccZt4G1E3r7d34SxiYiPbuhKqnRZk/nQ5Cfmc1rw3xtCjL0fKWwl3UVtLo/dkfV5PUkIk9pGXCpnKPLyq/5ai4tVQvPdrieRg9VU5qMfdMAUQ4h3gAx5rNK4z+H0tg4QVSpCtqIzeVtyu2Qt/HohY2eUgxmu0kiMDOBGb54D7XnnUsZn3b8Y4+RX1qz564I98208q1MD33VrO5mdHnEG+VeKxRNJwUw3JYKOA+ZEnqrZ4PBi3cV0MlmRlyktO6By6iZ4s/mW/4AOUZJZVoD/l2Q+VoJIWKTiJ1fGGk0DZMtcCeyEBM+typcf4EhNOOoEalhZn4pT3B9tECDcGp/SsRKxnkE2AdtEflLabS7Bt5S6CHffmZgviVtw6xZHb8ClloHMo=
    on_success: always # default: change
    on_failure: always # default: alway
    template:
      - - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}` by `%{author}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"
  email:
    on_success: never # default: change
    on_failure: never # default: alway


jobs:
    include:
        - stage: "Check the exitence of important files in Master branch"
          name: "RASD.pdf & DD.pdf"
          script:
              - for f in RASD/RASD-*.pdf; do [ -e "$f" ] && return 0 || return ; break ;done
              - for f in DeliveryFolder/RASD_*.pdf; do [ -e "$f" ] && return 0 || return ; break ;done
              - for f in DD/DD-*.pdf; do [ -e "$f" ] && return 0 || return ; break ;done
              - for f in DeliveryFolder/DD_*.pdf; do [ -e "$f" ] && return 0 || return ; break ;done
        - stage: GitHub Release
          before_deploy:
            - git config --local user.name "Deploy BOT"
            - git config --local user.email "Iambot@hoho.bot"
            - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'Y%YM%mD%dH%HM%MS%S')}
            - git tag $TRAVIS_TAG

          deploy:
            provider: releases
            api_key:
              secure: HEiedeK5dd7ig88bNf8Xn3xgLzU3u73tWW+taVz9ISqkW0ueRISwJW6ojd8+zabuQmEcqSRyVtoOtRL+/g0bzNrtmt/NfCzju9ipACvoVsS/GU3hWHkqBjGCGNZQ9OS9WIvfgSs9UBymKUjqR3YRYqbB1DJyxm7Jo5MAEwzS7kuAAeI101Xho4fVqUfp1evLOrtwgS57KKYBt88hnf+55nXMBaKe3KA6pszbtSeOaAi/EHSR4DFkLpnBAZ8Q6iF8CYdZgNyb5VG6mIZV8isVId57fOkEbgyySHf1UbJFijGhjitsiaB9j/Hazj13IhvrI4DJyCxGy3EUb4+okwixetBbjtksrcW1TdZy3uydf7LYHcWxuIGPicKZ+tN0Tg9GDMkDjSdYxTwWvGCP8kHt6ykwiOiVPtLcgLzT1U8JvGh+c7VBbNMUbos4u98yZjiPsU2OQoHzY26yym5o0BEaNz9b01+XGcNRnpWynurzKsaqQdm9qnML/VQvJAbfTxoWWq1WsEXA7PazFGRY24sjkINBG14UyHSuKr1Q5/pmrLAxoG2bGlV54qVOXM/TCsfKBsbziwSi28NLbrAMtcdl8MpFj74ZNOmWR4xT5m4gAj4ipEFdhL7PmmgY9OusV20Iih4DmH/kLyCYtjM1f3p9AdGt0nQ4L54PiFYuZKkyMjE=
            file_glob: true
            file: "DeliveryFolder/*_*.pdf"
            skip_cleanup: true
            on:
              repo: karim-zakaria/MolaeiRahnemoonSaloma
              branch: ''
